### PR TITLE
(MODULES-7753) Prep for 1.0.0 release

### PR DESCRIPTION
**Pull request by michaeltlombardi**
This commit prepares the module for the 1.0.0 release,
the first supported release of this module.

### CODE REVIEW

**Comment by joshcooper** [comment]
Can we also bump puppet-agent#master to pull in the latest?

**Comment by michaeltlombardi** [comment]
@joshcooper good chance I'm not smart enough to follow, you're asking if it makes sense to bump the pinned version of this module in the agent?

**Comment by joshcooper** [comment]
Yep sorry, in https://github.com/puppetlabs/puppet-agent/blob/master/configs/components/module-puppetlabs-scheduled_task.json

**Comment by michaeltlombardi** [comment]
PR there is up!

https://github.com/puppetlabs/puppet-agent/pull/1519

**Pull request merged**
