### PR TITLE
(maint) Added page anchors for L10n-readiness

### PR DESCRIPTION
**Pull request by ehom**

### CODE REVIEW

**Comment by ehom** [comment]
These two item don't have a section to link to.

```
  * [What scheduled_task affects](#what-scheduled_task-affects)
  * [Setup requirements](#setup-requirements)
```

**Comment by joshcooper** [comment]
@ehom Could you delete the table of contents entries that you mentioned?

**Comment by ehom** [comment]
> @ehom Could you delete the table of contents entries that you mentioned?

Wlll do.

**Comment by joshcooper** [comment]
@jpogran or @michaeltlombardi could you review and merge?

**Pull request merged**
